spring:
  application:
    name: incognito-bot
  profiles:
    active: local
  data:
    redis:
      url: ${REDIS_URL:rediss://default:AbYjAAIncDJhMGNlZDZjODVhNmQ0MWQ3OTNhZjk3MjQ5NjFkNDQwM3AyNDY2Mjc@fair-catfish-46627.upstash.io:6379}

server:
  port: 8080

telegram:
  bot:
    token: ${BOT_TOKEN:8421019264:AAGxbmsnie_SjJx-N-qyYYCqREzpW6dibhY}
    username: ${BOT_USERNAME:IncAskBot}
    webhook:
      url: ${WEBHOOK_URL:https://seven-squids-hope.loca.lt/api/webhook}
      secret: ${WEBHOOK_SECRET:my_secret_token_123}
